name: push-pipeline

on:
  push:
    branches:
      - feature/*
      - fix/*
      - main

permissions:
  contents: read
  id-token: write
  pull-requests: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml